// =============================================================================
// PM2 Ecosystem конфигурация для CaloriesApp Backend
// Оптимизировано для высокой нагрузки: 4 PM2 процесса на разных портах
// =============================================================================
// Использование:
//   pm2 start ecosystem.config.js          # Запуск всех процессов
//   pm2 stop ecosystem.config.js           # Остановка всех
//   pm2 restart ecosystem.config.js        # Перезапуск всех
//   pm2 logs caloriesapp-backend-1         # Логи конкретного процесса
//   pm2 monit                              # Мониторинг
//   pm2 save                               # Сохранить для автозапуска
// =============================================================================

module.exports = {
  apps: [
    {
      name: 'caloriesapp-backend-1',
      script: 'venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 8000 --workers 2 --limit-concurrency 50 --backlog 1024',
      cwd: '/home/scroll/backend',
      interpreter: 'none',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        PYTHONDONTWRITEBYTECODE: '1',
        PYTHONOPTIMIZE: '1',
        PYTHONHASHSEED: 'random',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      error_file: './logs/pm2-error-1.log',
      out_file: './logs/pm2-out-1.log',
      log_file: './logs/pm2-combined-1.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '30s',
      max_restarts: 15,
      restart_delay: 3000,
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      pmx: true,
    },
    {
      name: 'caloriesapp-backend-2',
      script: 'venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 8001 --workers 2 --limit-concurrency 50 --backlog 1024',
      cwd: '/home/scroll/backend',
      interpreter: 'none',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        PYTHONDONTWRITEBYTECODE: '1',
        PYTHONOPTIMIZE: '1',
        PYTHONHASHSEED: 'random',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      error_file: './logs/pm2-error-2.log',
      out_file: './logs/pm2-out-2.log',
      log_file: './logs/pm2-combined-2.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '30s',
      max_restarts: 15,
      restart_delay: 3000,
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      pmx: true,
    },
    {
      name: 'caloriesapp-backend-3',
      script: 'venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 8002 --workers 2 --limit-concurrency 50 --backlog 1024',
      cwd: '/home/scroll/backend',
      interpreter: 'none',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        PYTHONDONTWRITEBYTECODE: '1',
        PYTHONOPTIMIZE: '1',
        PYTHONHASHSEED: 'random',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      error_file: './logs/pm2-error-3.log',
      out_file: './logs/pm2-out-3.log',
      log_file: './logs/pm2-combined-3.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '30s',
      max_restarts: 15,
      restart_delay: 3000,
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      pmx: true,
    },
    {
      name: 'caloriesapp-backend-4',
      script: 'venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 8003 --workers 2 --limit-concurrency 50 --backlog 1024',
      cwd: '/home/scroll/backend',
      interpreter: 'none',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        PYTHONDONTWRITEBYTECODE: '1',
        PYTHONOPTIMIZE: '1',
        PYTHONHASHSEED: 'random',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      error_file: './logs/pm2-error-4.log',
      out_file: './logs/pm2-out-4.log',
      log_file: './logs/pm2-combined-4.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '30s',
      max_restarts: 15,
      restart_delay: 3000,
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      pmx: true,
    },
  ]
};
